name: Deploy Webpack to Pages

on:
  push:
    branches: ["main"] # Altere para "master" se o nome da sua branch principal for master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Compilar projeto (Webpack Build)
        run: npm run build

      - name: Upload do artefato compilado
        uses: actions/upload-pages-artifact@v3
        with:
          # Se o seu projeto salvar os arquivos finais na pasta 'build' em vez de 'dist', mude abaixo para './build'
          path: './dist' 

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Implantar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
